In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
print(os.listdir('./newsgroups'))

['.DS_Store', 'testClasses.txt', 'trainClasses.txt', 'testMatrix.txt', 'terms.txt', 'trainMatrix.txt', 'readme.txt']


In [4]:
np.loadtxt('./newsgroups/trainMatrix.txt')

array([[2., 0., 0., ..., 0., 0., 0.],
       [2., 0., 0., ..., 0., 0., 0.],
       [2., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
np.loadtxt('./newsgroups/trainClasses.txt')

array([[  0.,   0.],
       [  1.,   1.],
       [  2.,   0.],
       ...,
       [797.,   1.],
       [798.,   1.],
       [799.,   1.]])

In [6]:
np.loadtxt('./newsgroups/testMatrix.txt')

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
np.loadtxt('./newsgroups/testClasses.txt')

array([[  0.,   1.],
       [  1.,   0.],
       [  2.,   0.],
       [  3.,   1.],
       [  4.,   1.],
       [  5.,   0.],
       [  6.,   1.],
       [  7.,   1.],
       [  8.,   0.],
       [  9.,   1.],
       [ 10.,   0.],
       [ 11.,   1.],
       [ 12.,   0.],
       [ 13.,   0.],
       [ 14.,   1.],
       [ 15.,   1.],
       [ 16.,   0.],
       [ 17.,   1.],
       [ 18.,   0.],
       [ 19.,   0.],
       [ 20.,   0.],
       [ 21.,   0.],
       [ 22.,   0.],
       [ 23.,   0.],
       [ 24.,   1.],
       [ 25.,   1.],
       [ 26.,   1.],
       [ 27.,   0.],
       [ 28.,   1.],
       [ 29.,   1.],
       [ 30.,   1.],
       [ 31.,   0.],
       [ 32.,   0.],
       [ 33.,   0.],
       [ 34.,   1.],
       [ 35.,   0.],
       [ 36.,   0.],
       [ 37.,   1.],
       [ 38.,   1.],
       [ 39.,   1.],
       [ 40.,   1.],
       [ 41.,   0.],
       [ 42.,   1.],
       [ 43.,   0.],
       [ 44.,   0.],
       [ 45.,   1.],
       [ 46.,   1.],
       [ 47.,

In [3]:
trainMatrix = np.loadtxt('./newsgroups/trainMatrix.txt').T
pd.DataFrame(trainMatrix)

0     1     2     3     4     5     6     7     8     9     ...  5490  \
0     2.0   2.0   2.0   1.0   8.0   6.0   2.0   8.0   2.0   4.0  ...   0.0   
1     0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2     0.0   0.0   0.0   1.0   0.0   0.0   0.0   2.0   0.0   1.0  ...   0.0   
3     2.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4     2.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
795   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
796   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
797   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
798   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
799   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

     5491  5492  5493  5494  5495  5496  5497  5498  5499  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
795   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
796   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
797   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
798   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
799   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[800 rows x 5500 columns]

In [8]:
trainClasses = np.loadtxt('./newsgroups/trainClasses.txt')[:,1]
pd.DataFrame(trainClasses)

0
0    0.0
1    1.0
2    0.0
3    1.0
4    0.0
..   ...
795  0.0
796  1.0
797  1.0
798  1.0
799  1.0

[800 rows x 1 columns]

In [9]:
testMatrix = np.loadtxt('./newsgroups/testMatrix.txt').T
pd.DataFrame(testMatrix)

0     1     2     3     4     5     6     7     8     9     ...  5490  \
0     0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0  ...   0.0   
1     0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2     1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3     0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4     0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0  ...   0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
195   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0  ...   1.0   
196   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
197   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
198   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0  ...   0.0   
199   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

     5491  5492  5493  5494  5495  5496  5497  5498  5499  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
195   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
196   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
197   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
198   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
199   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[200 rows x 5500 columns]

In [10]:
testClasses = np.loadtxt('./newsgroups/testClasses.txt')[:,1]
pd.DataFrame(testClasses)

0
0    1.0
1    0.0
2    0.0
3    1.0
4    1.0
..   ...
195  1.0
196  1.0
197  0.0
198  1.0
199  1.0

[200 rows x 1 columns]

In [11]:
trainMatrix.shape, trainClasses.shape, testMatrix.shape, testClasses.shape

((800, 5500), (800,), (200, 5500), (200,))

In [12]:
def naiveBayesTrain(X, y):
    prior = []
    n_voc = X.shape[1]
    pwc = np.zeros((n_voc, 2))
    for i in [0, 1]:
        prior.append(np.mean(y == i))
        docs = X[y == i]
        n_i = docs.sum() # total number of words
        pwc[:,i] = (docs.sum(axis=0) + 1)/(n_i + n_voc)
    
    return prior, pwc

def naiveBayesPredict(prior, pwc, X):
    preds = []
    for j in range(X.shape[0]):
        preds.append(1*(np.log(prior[1]/prior[0])+ sum(np.log(pwc[:,1]/pwc[:,0])*X[j]) > 0))
    return np.array(preds)

In [13]:
# train naive bayes model and determine the probabilities
prior, pwc = naiveBayesTrain(trainMatrix, trainClasses)

In [14]:
# predict the class on the test using the trained parameters
y_pred = naiveBayesPredict(prior, pwc, testMatrix)

### Part 1

In [15]:
print('Test set accuracy:', np.mean(y_pred == testClasses))

Test set accuracy: 0.995


### Part 2

In [16]:
print(pd.DataFrame({'actual': testClasses, 'predicted': y_pred}).astype(int).head(20))

    actual  predicted
0        1          1
1        0          0
2        0          0
3        1          1
4        1          1
5        0          0
6        1          1
7        1          1
8        0          0
9        1          1
10       0          0
11       1          1
12       0          0
13       0          0
14       1          1
15       1          1
16       0          0
17       1          1
18       0          0
19       0          0


### Part 3

In [17]:
terms = pd.read_csv('./newsgroups/terms.txt', header=None)[0].values.tolist()
terms[:3]

['david', 'rex', 'wood']

In [18]:
probs = []
words = ["program", "includ", "match", "game", "plai", "window", "file", "subject", "write"]
for item in words:
    indx = terms.index(item)
    probs.append(pwc[indx,].tolist())

In [19]:
print(pd.DataFrame(probs, index=words))

                0         1
program  0.005902  0.000110
includ   0.005266  0.000697
match    0.000236  0.000385
game     0.000218  0.012291
plai     0.000127  0.007265
window   0.013057  0.000055
file     0.006701  0.000055
subject  0.009843  0.007687
write    0.003777  0.005082
